// ── Nav active state ──
  (function() {
    const anchors = document.querySelectorAll('.nav-anchor');
    const sectionIds = ['intro','s00','s01','s02','s03'];
    const sections = sectionIds.map(id => document.getElementById(id));
    const navEl = document.querySelector('.nav');
    function update() {
      const navH = navEl ? navEl.offsetHeight : 57;
      const scrollY = window.scrollY + navH + 40;
      const atBottom = window.scrollY + window.innerHeight >= document.body.scrollHeight - 60;
      let active = sections[0];
      if (atBottom) {
        active = sections[sections.length - 1];
      } else {
        sections.forEach(sec => { if (sec && sec.offsetTop <= scrollY) active = sec; });
      }
      anchors.forEach(a => {
        a.classList.toggle('active', a.getAttribute('href') === '#' + (active ? active.id : ''));
      });
    }
    window.addEventListener('scroll', update, { passive: true });
    update();
  })();

  // ── i18n ──
  (function() {
    const dataAppsI18n = {
      'zh-tw': {
        'nav.intro': '.介紹', 'nav.s00': '01.緣起', 'nav.s01': '02.探索', 'nav.s02': '03.對話', 'nav.s03': '04.Artifact', 'nav.s04': '05.下鑽', 'nav.s05': '06.生命週期',
        'page.title': 'Data Apps',
        'page.subtitle': '用對話搭建、用直接操作微調的活 BI 畫布。',
        'intro.label.product': '產品簡介｜對話式智慧儀表板',
        'intro.product.body': 'Data Apps 是一款由 AI 驅動的「活儀表板」。使用者不需撰寫 SQL 或手動拖拉元件，只需用自然語言描述需求（例如：「各 VP 的目標達成率，並依地區篩選」），AI 就會自動組裝出包含圖表、KPI、篩選器與下鑽路徑的連動儀表板。它成功將過去「一問一答」的單次數據查詢，升級為能持續對話、動態探索的全新 BI 介面。',
        'intro.label.role': '我的角色｜端到端 (End-to-End) 體驗設計師',
        'intro.role.body': '我主導 Data Apps 從 0 到 1 的畫布體驗設計，主要貢獻包含：<br><b>擘畫完整用戶旅程：</b>梳理並設計橫跨 <span class="stat-hi">13 個互動階段</span> 的顧客旅程地圖（Journey Map），涵蓋從對話喚醒 AI、生成畫布、圖表下鑽，到最終成品的儲存、分享與管理。<br><b>設計雙軌互動模型：</b>打造無縫結合「AI 對話指令」與「直接點擊操作」的雙重控制介面，讓使用者在同一個畫布上，能以最直覺的方式持續編輯與探索數據。',
        'intro.label.time': '時間範圍：',
        'intro.time.body': '2026.4–2026.6',
        's00.title': '一切的起點',
        's00.lede': 'Data Apps 並不是先有功能構想，而是從客戶的回饋裡長出來的。在質性訪談中，同一幅畫面一再浮現：每個團隊都仰賴幾張由數據分析師親手搭建的儀表板，而只要其中一張需要變動，整個組織就被卡在 <span class="stat-hi-blue">同一個人</span> 身上。',
        's00.cap': '客戶自家報表的其中一張示意：一張由數據分析師在 Power BI 中親手搭建的 GPS 完成率儀表板。',
        's00.f1.label': '難以維護',
        's00.f1.body': '每一次指標調整、每個月進來的新資料、每一條斷掉的 join，都得回到當初搭建這個檔案的分析師手上。其他人都不敢輕易動它。',
        's00.f2.label': '搭建成本高',
        's00.f2.body': '光是一張儀表板就要耗掉分析師好幾天：蒐集需求、建資料模型，再把篩選器與下鑽路徑一個一個手動接起來。',
        's00.f3.label': '上線即定型',
        's00.f3.body': '一旦上線，報表幾乎就被鎖死了。想多加一個維度、換一種切法，都得把整個搭建流程重開一次，於是多數修改需求就這樣無聲地消失。',
        's00.close': '而當另一個單位需要自己的視角時，他們做不出來，只能提需求、排進分析師的待辦佇列，然後往往就放棄了。Data Apps 最初的提問正是從這裡來的：如果需要這張報表的人，能直接用講的把它描述出來，並拿回一張真正、會持續存活的儀表板，會怎麼樣？',
        's01.title': 'Vibe Coding：快速探索、與用戶共創',
        's01.lede': '與其把 Data Apps 畫成一張張靜態 mockup、再祈禱它感覺對了，我選擇直接做出來驗證。透過 vibe coding，我在幾天內就把每個想法變成可點擊的原型，擺到真實的營運用戶面前，讓他們的反應重新畫出整個流程。最後上線的，是在這個循環裡存活下來的版本，而不是我最初畫的那一版。',
        's01.body': '這個循環刻意維持得很快、也不怕弄壞。我會先 vibe code 出一個版本，坐在用戶旁邊看他們拿自己的資料去試，觀察他們在哪裡猶豫、伸手去點什麼、又忽略了什麼。這裡的共創不是辦一場工作坊，而是先丟出一個粗糙的版本，讓它在真實情境裡撞碎，隔天早上再重做一遍。其中有兩個原型版本值得並排來看，因為它們之間的落差，正是整件事的重點。',
        's01.prior.label': '舊的做法：一次一張圖表',
        's01.prior.body': '其實你早就能用手動的方式做到一部分。先問一個問題，例如「各州顧客的付款總額是多少？」，等表格回來，再追問「幫我生成一張圖表」把它變成長條圖，最後按下 <b>Pin to dashboard</b>，開一個新的「Payment Analysis Dashboard」。圖表就會被釘上儀表板，完整呈現出來。',
        's01.prior.cost': '但那只是一張圖表。要重現一個你先前在 BI 工具裡搭好的儀表板，等於每一格都得把整個流程再跑一次；而且唯有你一開始就清楚知道完成後的儀表板該長什麼樣、也知道每一張圖要用什麼問題問出來，這條路才走得通。舊流程能回答你，卻無法替你扛起整個規劃。Data Apps 補上了這個落差：你只要描述一次儀表板，畫布就會把彼此連動的整體組起來。',
        's01.now.label': '新的做法：一句指令，整份報表',
        's01.now.body': '現在你交給 agent 的是目標，而不是步驟。你只要下一個指令 <code>/generate-report</code>，用一句話描述想要的結果，例如「各 VP 的 GPS 完成率，再依辦公室與地區拆分」。接下來 agent 會自己規劃：把需求拆成幾組彙總、把查詢並行跑完、為每一個切面挑一張合適的圖表，最後組成一份完整的報表。光是上面那一句，就產出了一份過去客戶得在 Power BI 手刻的 GPS 完成率報表：每位 VP 對照目標的完成率趨勢，並附上辦公室與地區的拆分，而我不必逐一指定每張圖、也不必寫任何 SQL。過去舊流程丟給我的規劃，現在都交由 agent 一手扛起。',
        's01.flows.label': '兩個版本，同一個儀表板',
        's01.flows.body': '要做的事情從來沒變：團隊需要一個能持續使用的儀表板。改變的是，提出需求的人得自己扛下多少工作。在這兩個版本之間，規劃的重擔逐步從需求方移到了系統身上。',
        's01.f1.tag': '使用 Data Apps 之前',
        's01.f1.h': '提出需求，然後排隊等候',
        's01.f1.s1': '把需求描述給數據分析師',
        's01.f1.s2': '在分析師的待辦清單裡排隊',
        's01.f1.s3': '常常就放棄了',
        's01.f1.b': '需要這份報表的人，自己做不出來。每個團隊都仰賴幾張手工搭好的儀表板，而整個組織都被卡在同一位分析師身上。',
        's01.f2.tag': 'Ver. 1',
        's01.f2.h': 'Ask → Chart → Pin，一次一張圖',
        's01.f2.s1': '問一個問題，拿到一張表',
        's01.f2.s2': '說「幫我生成一張圖表」把它畫出來',
        's01.f2.s3': '按下 Pin to dashboard，再重複一次',
        's01.f2.b': '總算能自助了，但一次只能生出一張圖。要重建一整個儀表板，等於每一格都得把整個流程再跑一遍，而且唯有你一開始就知道每個問題該怎麼問才行得通。',
        's01.f3.tag': 'Ver. 2',
        's01.f3.h': '一句指令：/generate-report',
        's01.f3.s1': '用一句話描述想要的結果',
        's01.f3.s2': 'agent 自行規劃並行查詢',
        's01.f3.s3': '一份完成的報表就此產出',
        's01.f3.b': '你交出的是目標，而不是步驟。agent 會把需求拆成幾組彙總、並行跑完查詢、為每一個切面挑一張圖表，最後回給你一份完整的報表。',
        's01.flows.cap': '光是一句 /generate-report，就回給了這份完整的 GPS 完成率報表：每位 VP 對照目標的完成率趨勢，並附上辦公室與地區切片。',
        's01.old.h': '之前 · Ask Data',
        's01.old.lead': '一個問題 → 一個答案',
        's01.old.i1': '每一輪都從零開始，沒有共享狀態',
        's01.old.i2': '答案只被讀一次，接著就被捲走',
        's01.old.i3': '圖表之間沒有共用的篩選器',
        's01.old.i4': '想換一個維度，得把整個問題重問一次',
        's01.new.h': '之後 · Data Apps Canvas',
        's01.new.lead': '一句 prompt → 一張活儀表板',
        's01.new.i1': '畫布在整個對話中持續存在',
        's01.new.i2': '圖表、KPI、篩選器與下鑽路徑彼此連動',
        's01.new.i3': '篩選器一次串連到每一張圖表',
        's01.new.i4': '直接對畫布上既有的內容說話，就能換維度',
        's02.title': '設計決策一：對話介面該放哪？',
        's02.lede': '我最初的設計，是把一個聊天面板停靠在儀表板右側，這是最理所當然的版面，幾乎每個外掛了助理的 BI 工具都這樣做。但它是錯的：側邊面板會跟畫布搶寬度，也把對話和它生出來的 artifact 硬生生切開。於是我把對話移進那條本來就保存著它歷史的 thread 裡，並讓控制權在裡面一分為二，因為 <span class="stat-hi">對話擅長表達意圖，卻不擅長精準操作。</span>',
        's02.c.label': '用對話表達意圖',
        's02.c.body': '聊天輸入框驅動整張畫布。描述一個儀表板，它就被生成；說「只看七月到十二月」，每張圖都重新同步；說「展開 Cathy Spinney」，畫面就下鑽進去。任何「用說的比在選單裡找還快」的操作，都歸這裡。',
        's02.d.label': '用直接操作做到精準',
        's02.d.body': '但像素級、單張圖層級的工作屬於手，而非句子。<code>pick mode</code> 游標讓你點任一張卡片、KPI 或篩選列，把下一句 prompt 的範圍鎖定到那一個區塊。鉛筆會打開一個 <span class="stat-hi-blue">控制項依圖表類型而定的行內樣式面板</span>：長條圖給圓角、折線圖給曲線類型、圓餅圖給甜甜圈孔，你用不到的控制項永遠不會出現。卡片可拖曳重排，並設了 5px 門檻，讓點按鈕時絕不會誤觸成拖曳。',
        's02.cap': 'Pick mode（↖）把 prompt 鎖定到單一區塊 · 鉛筆打開該圖表類型專屬的控制項',
        's03.title': '設計決策二：把「一個儀表板」拆成「多個 artifact」',
        's03.lede': '最初的需求寫的是「dashboard」，單數：一塊你生成、你擁有的大儀表板。但看著用戶，我覺得這個概念太重了。他們要的不是一整塊，而是一塊塊能搬走、能重用、能分享的東西：這裡一張圖、那裡一個 KPI、為某場會議拼一份報表。於是我重新定義了產出：一個 Data App 不是一塊儀表板，而是 <span class="stat-hi">許多各自獨立的 artifact</span>，只是剛好共用同一張畫布。',
        's03.body': '把每個 artifact 都當成一級物件來對待，改變了系統必須追蹤的東西。一張圖不再被困在生出它的那塊儀表板裡：它有自己的身分、自己的擁有者，也在資料夾裡有自己的位置。正是這一點，讓「Start in new thread」或「Copy to another folder」變得有意義；也正因如此，分享必須回答一個更尖銳的問題。不是「誰能看到這塊儀表板？」，而是「對於一個不是你做的 artifact，你能拿它做什麼？」',
        's03.gen.label': '三種起點，同一個好結果',
        's03.gen.body': '從這裡開始，三種輸入品質都會收斂到同一個完整的儀表板：無論使用者是精準、含糊、還是介於兩者之間，終點都一樣。',
        's03.precise.tag': '精準',
        's03.precise.h': '一行寫完整規格',
        's03.precise.b': '「GPS 完成率依 VP 與 Office 的趨勢，可依 region 與 VP 篩選」一步就生成整個儀表板：兩張折線圖、一條月份導覽列、串連的 Region → VP → Office 篩選器、一個斷訊切換，以及一個全部清除。',
        's03.vague.tag': '含糊',
        's03.vague.h': '少講了一個字',
        's03.vague.b': '「GPS 完成率儀表板」會觸發一個釐清問題：「你想分析哪些維度？」，並把 VP、Office、Region、或以上皆是做成一點即選的 chip。',
        's03.clar.tag': '釐清之後',
        's03.clar.h': '同一個終點',
        's03.clar.b': '點「以上皆是」，就會落在跟精準 prompt 完全一樣的儀表板上。含糊的路徑只多花一次點擊，絕不需要重來。',
        's03.roll.label': '滾動式確認，而非擋路',
        's03.roll.body': '生成過程從不先停下來要授權。圖表一畫出來，系統就掃描維度階層，浮出兩條不擋路的建議流：<b>下鑽建議</b>（「點一條線之後該出現什麼？」）與 <b>圖表建議</b>（「你也可以加一張各 region 完成率長條圖」）。接受一個就加進去；其餘留著；略過就收合。儀表板在每一步都可用。這正是支撐 Wren AI Agent mode 的同一套 <span class="stat-hi-blue">滾動式確認</span> 模式。',
        's04.title': '下鑽這道難題',
        's04.lede': '下鑽是整個專案裡最難做對的單一互動。一張圖可以被下鑽，但系統往往不知道 <span class="stat-hi">點下去之後該去哪裡</span>，而強迫使用者預先定義每一層階層，又會毀掉「只要描述就好」的魔法。答案是把階層變成一個有三個入口的 <span class="stat-hi-blue">即時決策</span>。',
        's04.e1.t': '系統建議',
        's04.e1.b': '圖表畫出來的同時，系統偵測可下鑽的維度，並就地提議下一層。接受「Transaction detail」，下鑽路徑在使用者開口前就配置好了。',
        's04.e2.t': '在 prompt 裡宣告',
        's04.e2.b': '「各區域業績，點下去要下鑽到各 office」會在圖表搭建時就記下階層。下鑽圖示立刻出現，不需要額外的設定步驟。',
        's04.e3.t': '首次觸發',
        's04.e3.b': '使用者去下鑽一張從沒設定過的圖（「展開 Bayville」）。系統接住了：「這張圖還沒設下鑽，展開之後你想看什麼？」一回答，它就記下階層，並在同一個動作裡完成下鑽。',
        's04.chain.label': '當路徑是串接的',
        's04.chain.body': '面對多層路徑，輸入 <code>Drill down:</code> 會打開一個串接式的層級選擇器。選「By Region」，輸入框就變成 <code>Drill down: By Region → /</code> 並重新打開；接著再選「By Office」。已選過的層級會被隱藏以避免重複，麵包屑標頭顯示目前為止的路徑，按 Enter 一次套用整條鏈。',
        's04.undef.label': '當維度沒有下一層',
        's04.undef.body': '有些軸沒有明顯的子層。去下鑽「Month」軸，系統會老實承認：「Month 沒有預先定義的下一層，展開要顯示哪個欄位？」並給出 Week、Day、或從欄位清單挑選。一個誠實的死路，於是變成一次點擊的決定，而不是無聲的失敗。',
        's04.hier.label': '底層的階層結構',
        's04.hier.body': '這一切都建立在一個明確的父子模型上：一個 <code>Hierarchy Instruction</code> 層，在資料層定義彙總與展開，讓每一次點擊都落在正確上捲的視圖上。首發資料集的關鍵下鑽路徑深達五層：',
        's04.cap': '每一次點擊就往下彙總一層；麵包屑與一個邏輯追蹤器讓目前的路徑始終明確。',
        's05.title': '持續存活的儀表板',
        's05.lede': '儀表板一旦留存，它就有了生命：它會被篩選、被分享、被分支、被一再回訪。兩套系統讓它保持一致：絕不觸發重新查詢的 <span class="stat-hi">連動篩選</span>，以及一份清楚誰能編輯什麼的 <span class="stat-hi">具擁有權意識</span> 的 data apps 清單。',
        's05.filter.label': '篩選會串連，查詢不重跑',
        's05.filter.body': '篩選是對話式的、而且彼此連動。「只看 New England」會更新每一張圖，並把 VP 篩選器自動收窄到 New England 的 VP；Office 篩選器跟著動。「再篩到 Cathy Spinney」會把 By-VP 圖收到她那條線、Office 篩選器收到她的 office。因為篩選是 <span class="stat-hi-blue">在既有結果集上的動態連動</span>，相關圖表即時更新：不重新生成，也不為了每個小調整就重新查倉。',
        's05.own.label': '擁有者 vs 被分享者',
        's05.own.body': '每一張在 Agent mode 裡搭出來的畫布，都會被自動加進它所在資料夾的 Data apps 清單。你能對一列做什麼，取決於它是不是你搭的。擁有者拿到完整選單。對於只是被分享進你資料夾的 data app，<b>Edit 被刻意隱藏</b>：你打不開別人的來源對話，所以選單提供 Start in new thread、Copy，以及一個只會從你自己資料夾移除它的 Delete。',
        's05.next.label': '接下來呢',
        's05.next.body': '有兩項能力就在首發之外，已設計好、但定位為加分項而暫緩：<b>AI insight</b> 會用白話摘要為一張圖加註，並為正在變動的數據標出「Where to focus」；以及 <b>排程式 Insight Reports</b>，按設定的頻率把儀表板快照寄到 email 或推播，讓這張活儀表板，也能觸及那些從不打開畫布的人。',
        's05.reflect': '回頭看，Data Apps 其實不是在 mockup 裡設計出來的。它是靠動手做被發掘出來、拿去和真實用戶對撞測試，最後在幾個小小的賭注上做出決定：對話該住在哪裡、一個產出的單位該有多大。真正有意思的工作從來不是畫圖表，而是一次又一次地，選出那個能讓使用它的人，清楚知道下一步該往哪走的版本。',
      },
      'zh-cn': {
        'nav.intro': '.介绍', 'nav.s00': '01.缘起', 'nav.s01': '02.探索', 'nav.s02': '03.对话', 'nav.s03': '04.Artifact', 'nav.s04': '05.下钻', 'nav.s05': '06.生命周期',
        'page.title': 'Data Apps',
        'page.subtitle': '用对话搭建、用直接操作微调的活 BI 画布。',
        'intro.label.product': '产品简介｜对话式智能仪表板',
        'intro.product.body': 'Data Apps 是一款由 AI 驱动的"活仪表板"。用户无需撰写 SQL 或手动拖拽组件，只需用自然语言描述需求（例如："各 VP 的目标达成率，并按地区筛选"），AI 就会自动组装出包含图表、KPI、筛选器与下钻路径的联动仪表板。它成功将过去"一问一答"的单次数据查询，升级为能持续对话、动态探索的全新 BI 界面。',
        'intro.label.role': '我的角色｜端到端 (End-to-End) 体验设计师',
        'intro.role.body': '我主导 Data Apps 从 0 到 1 的画布体验设计，主要贡献包含：<br><b>擘画完整用户旅程：</b>梳理并设计横跨 <span class="stat-hi">13 个交互阶段</span> 的客户旅程地图（Journey Map），涵盖从对话唤醒 AI、生成画布、图表下钻，到最终成品的保存、分享与管理。<br><b>设计双轨交互模型：</b>打造无缝结合"AI 对话指令"与"直接点击操作"的双重控制界面，让用户在同一个画布上，能以最直觉的方式持续编辑与探索数据。',
        'intro.label.time': '时间范围：',
        'intro.time.body': '2026.4–2026.6',
        's00.title': '一切的起点',
        's00.lede': 'Data Apps 并不是先有功能构想，而是从客户的反馈里长出来的。在质性访谈中，同一幅画面一再浮现：每个团队都依赖几张由数据分析师亲手搭建的仪表板，而只要其中一张需要变动，整个组织就被卡在 <span class="stat-hi-blue">同一个人</span> 身上。',
        's00.cap': '客户自家报表的其中一张示意：一张由数据分析师在 Power BI 中亲手搭建的 GPS 完成率仪表板。',
        's00.f1.label': '难以维护',
        's00.f1.body': '每一次指标调整、每个月进来的新数据、每一条断掉的 join，都得回到当初搭建这个文件的分析师手上。其他人都不敢轻易动它。',
        's00.f2.label': '搭建成本高',
        's00.f2.body': '光是一张仪表板就要耗掉分析师好几天：收集需求、建数据模型，再把筛选器与下钻路径一个一个手动接起来。',
        's00.f3.label': '上线即定型',
        's00.f3.body': '一旦上线，报表几乎就被锁死了。想多加一个维度、换一种切法，都得把整个搭建流程重开一次，于是多数修改需求就这样无声地消失。',
        's00.close': '而当另一个单位需要自己的视角时，他们做不出来，只能提需求、排进分析师的待办队列，然后往往就放弃了。Data Apps 最初的提问正是从这里来的：如果需要这张报表的人，能直接用说的把它描述出来，并拿回一张真正、会持续存活的仪表板，会怎么样？',
        's01.title': 'Vibe Coding：快速探索、与用户共创',
        's01.lede': '与其把 Data Apps 画成一张张静态 mockup、再祈祷它感觉对了，我选择直接做出来验证。通过 vibe coding，我在几天内就把每个想法变成可点击的原型，摆到真实的运营用户面前，让他们的反应重新画出整个流程。最后上线的，是在这个循环里存活下来的版本，而不是我最初画的那一版。',
        's01.body': '这个循环刻意维持得很快、也不怕弄坏。我会先 vibe code 出一个版本，坐在用户旁边看他们拿自己的数据去试，观察他们在哪里犹豫、伸手去点什么、又忽略了什么。这里的共创不是办一场工作坊，而是先丢出一个粗糙的版本，让它在真实情境里撞碎，隔天早上再重做一遍。其中有两个原型版本值得并排来看，因为它们之间的落差，正是整件事的重点。',
        's01.prior.label': '旧的做法：一次一张图表',
        's01.prior.body': '其实你早就能用手动的方式做到一部分。先问一个问题，例如"各州顾客的付款总额是多少？"，等表格回来，再追问"帮我生成一张图表"把它变成柱状图，最后点下 <b>Pin to dashboard</b>，新建一个"Payment Analysis Dashboard"。图表就会被钉上仪表板，完整渲染出来。',
        's01.prior.cost': '但那只是一张图表。要重现一个你先前在 BI 工具里搭好的仪表板，等于每一格都得把整个流程再跑一次；而且只有当你一开始就清楚知道完成后的仪表板该长什么样、也知道每一张图要用什么问题问出来，这条路才走得通。旧流程能回答你，却无法替你扛起整个规划。Data Apps 补上了这个落差：你只要描述一次仪表板，画布就会把彼此联动的整体组起来。',
        's01.now.label': '新的做法：一条命令，整份报表',
        's01.now.body': '现在你交给 agent 的是目标，而不是步骤。你只要运行一条命令 <code>/generate-report</code>，用一句话描述想要的结果，比如“各 VP 的 GPS 完成率，再按办公室与地区拆分”。接下来 agent 会自己规划：把需求拆成几组聚合、把查询并行跑完、为每一个切面挑一张合适的图表，最后组装成一份完整的报表。仅仅上面这一句，就产出了一份过去客户得在 Power BI 手工搭建的 GPS 完成率报表：每位 VP 对照目标的完成率趋势，并附上办公室与地区的拆分，而我无需逐一指定每张图、也无需写任何 SQL。过去旧流程丢给我的规划，现在都由 agent 一手扛起。',
        's01.flows.label': '两个版本，同一个仪表板',
        's01.flows.body': '要做的事情从来没变：团队需要一个能持续使用的仪表板。改变的是，提出需求的人得自己扛下多少工作。在这两个版本之间，规划的重担逐步从需求方移到了系统身上。',
        's01.f1.tag': '使用 Data Apps 之前',
        's01.f1.h': '提出需求，然后排队等候',
        's01.f1.s1': '把需求描述给数据分析师',
        's01.f1.s2': '在分析师的待办清单里排队',
        's01.f1.s3': '常常就放弃了',
        's01.f1.b': '需要这份报表的人，自己做不出来。每个团队都依赖几张手工搭好的仪表板，而整个组织都被卡在同一位分析师身上。',
        's01.f2.tag': 'Ver. 1',
        's01.f2.h': 'Ask → Chart → Pin，一次一张图',
        's01.f2.s1': '问一个问题，拿到一张表',
        's01.f2.s2': '说“帮我生成一张图表”把它画出来',
        's01.f2.s3': '点下 Pin to dashboard，再重复一次',
        's01.f2.b': '总算能自助了，但一次只能生出一张图。要重建一整个仪表板，等于每一格都得把整个流程再跑一遍，而且只有当你一开始就知道每个问题该怎么问才行得通。',
        's01.f3.tag': 'Ver. 2',
        's01.f3.h': '一条命令：/generate-report',
        's01.f3.s1': '用一句话描述想要的结果',
        's01.f3.s2': 'agent 自行规划并行查询',
        's01.f3.s3': '一份完成的报表就此产出',
        's01.f3.b': '你交出的是目标，而不是步骤。agent 会把需求拆成几组聚合、并行跑完查询、为每一个切面挑一张图表，最后回给你一份完整的报表。',
        's01.flows.cap': '仅仅一句 /generate-report，就回给了这份完整的 GPS 完成率报表：每位 VP 对照目标的完成率趋势，并附上办公室与地区切片。',
        's01.old.h': '之前 · Ask Data',
        's01.old.lead': '一个问题 → 一个答案',
        's01.old.i1': '每一轮都从零开始，没有共享状态',
        's01.old.i2': '答案只被读一次，接着就被滚走',
        's01.old.i3': '图表之间没有共用的筛选器',
        's01.old.i4': '想换一个维度，得把整个问题重问一次',
        's01.new.h': '之后 · Data Apps Canvas',
        's01.new.lead': '一句 prompt → 一张活仪表板',
        's01.new.i1': '画布在整个对话中持续存在',
        's01.new.i2': '图表、KPI、筛选器与下钻路径彼此联动',
        's01.new.i3': '筛选器一次串联到每一张图表',
        's01.new.i4': '直接对画布上既有的内容说话，就能换维度',
        's02.title': '设计决策一：对话界面该放哪？',
        's02.lede': '我最初的设计，是把一个聊天面板停靠在仪表板右侧，这是最理所当然的版面，几乎每个外挂了助理的 BI 工具都这样做。但它是错的：侧边面板会跟画布抢宽度，也把对话和它生出来的 artifact 硬生生切开。于是我把对话移进那条本来就保存着它历史的 thread 里，并让控制权在里面一分为二，因为 <span class="stat-hi">对话擅长表达意图，却不擅长精准操作。</span>',
        's02.c.label': '用对话表达意图',
        's02.c.body': '聊天输入框驱动整张画布。描述一个仪表板，它就被生成；说"只看七月到十二月"，每张图都重新同步；说"展开 Cathy Spinney"，画面就下钻进去。任何"用说的比在菜单里找还快"的操作，都归这里。',
        's02.d.label': '用直接操作做到精准',
        's02.d.body': '但像素级、单张图层级的工作属于手，而非句子。<code>pick mode</code> 光标让你点任一张卡片、KPI 或筛选栏，把下一句 prompt 的范围锁定到那一个区块。铅笔会打开一个 <span class="stat-hi-blue">控制项随图表类型而定的行内样式面板</span>：柱状图给圆角、折线图给曲线类型、饼图给甜甜圈孔，你用不到的控制项永远不会出现。卡片可拖拽重排，并设了 5px 阈值，让点按钮时绝不会误触成拖拽。',
        's02.cap': 'Pick mode（↖）把 prompt 锁定到单一区块 · 铅笔打开该图表类型专属的控制项',
        's03.title': '设计决策二：把"一个仪表板"拆成"多个 artifact"',
        's03.lede': '最初的需求写的是"dashboard"，单数：一块你生成、你拥有的大仪表板。但看着用户，我觉得这个概念太重了。他们要的不是一整块，而是一块块能搬走、能重用、能分享的东西：这里一张图、那里一个 KPI、为某场会议拼一份报表。于是我重新定义了产出：一个 Data App 不是一块仪表板，而是 <span class="stat-hi">许多各自独立的 artifact</span>，只是刚好共用同一张画布。',
        's03.body': '把每个 artifact 都当成一级对象来对待，改变了系统必须追踪的东西。一张图不再被困在生出它的那块仪表板里：它有自己的身份、自己的所有者，也在文件夹里有自己的位置。正是这一点，让"Start in new thread"或"Copy to another folder"变得有意义；也正因如此，分享必须回答一个更尖锐的问题。不是"谁能看到这块仪表板？"，而是"对于一个不是你做的 artifact，你能拿它做什么？"',
        's03.gen.label': '三种起点，同一个好结果',
        's03.gen.body': '从这里开始，三种输入质量都会收敛到同一个完整的仪表板：无论用户是精准、含糊、还是介于两者之间，终点都一样。',
        's03.precise.tag': '精准',
        's03.precise.h': '一行写完整规格',
        's03.precise.b': '"GPS 完成率按 VP 与 Office 的趋势，可按 region 与 VP 筛选"一步就生成整个仪表板：两张折线图、一条月份导航栏、串联的 Region → VP → Office 筛选器、一个断讯开关，以及一个全部清除。',
        's03.vague.tag': '含糊',
        's03.vague.h': '少讲了一个字',
        's03.vague.b': '"GPS 完成率仪表板"会触发一个澄清问题："你想分析哪些维度？"，并把 VP、Office、Region、或以上皆是做成一点即选的 chip。',
        's03.clar.tag': '澄清之后',
        's03.clar.h': '同一个终点',
        's03.clar.b': '点"以上皆是"，就会落在跟精准 prompt 完全一样的仪表板上。含糊的路径只多花一次点击，绝不需要重来。',
        's03.roll.label': '滚动式确认，而非挡路',
        's03.roll.body': '生成过程从不先停下来要授权。图表一画出来，系统就扫描维度层级，浮出两条不挡路的建议流：<b>下钻建议</b>（"点一条线之后该出现什么？"）与 <b>图表建议</b>（"你也可以加一张各 region 完成率柱状图"）。接受一个就加进去；其余留着；略过就收合。仪表板在每一步都可用。这正是支撑 Wren AI Agent mode 的同一套 <span class="stat-hi-blue">滚动式确认</span> 模式。',
        's04.title': '下钻这道难题',
        's04.lede': '下钻是整个项目里最难做对的单一交互。一张图可以被下钻，但系统往往不知道 <span class="stat-hi">点下去之后该去哪里</span>，而强迫用户预先定义每一层层级，又会毁掉"只要描述就好"的魔法。答案是把层级变成一个有三个入口的 <span class="stat-hi-blue">即时决策</span>。',
        's04.e1.t': '系统建议',
        's04.e1.b': '图表画出来的同时，系统检测可下钻的维度，并就地提议下一层。接受"Transaction detail"，下钻路径在用户开口前就配置好了。',
        's04.e2.t': '在 prompt 里声明',
        's04.e2.b': '"各区域业绩，点下去要下钻到各 office"会在图表搭建时就记下层级。下钻图标立刻出现，不需要额外的设置步骤。',
        's04.e3.t': '首次触发',
        's04.e3.b': '用户去下钻一张从没设置过的图（"展开 Bayville"）。系统接住了："这张图还没设下钻，展开之后你想看什么？"一回答，它就记下层级，并在同一个动作里完成下钻。',
        's04.chain.label': '当路径是串接的',
        's04.chain.body': '面对多层路径，输入 <code>Drill down:</code> 会打开一个串接式的层级选择器。选"By Region"，输入框就变成 <code>Drill down: By Region → /</code> 并重新打开；接着再选"By Office"。已选过的层级会被隐藏以避免重复，面包屑标头显示目前为止的路径，按 Enter 一次套用整条链。',
        's04.undef.label': '当维度没有下一层',
        's04.undef.body': '有些轴没有明显的子层。去下钻"Month"轴，系统会老实承认："Month 没有预先定义的下一层，展开要显示哪个字段？"并给出 Week、Day、或从字段列表挑选。一个诚实的死路，于是变成一次点击的决定，而不是无声的失败。',
        's04.hier.label': '底层的层级结构',
        's04.hier.body': '这一切都建立在一个明确的父子模型上：一个 <code>Hierarchy Instruction</code> 层，在数据层定义汇总与展开，让每一次点击都落在正确上卷的视图上。首发数据集的关键下钻路径深达五层：',
        's04.cap': '每一次点击就往下汇总一层；面包屑与一个逻辑追踪器让目前的路径始终明确。',
        's05.title': '持续存活的仪表板',
        's05.lede': '仪表板一旦留存，它就有了生命：它会被筛选、被分享、被分支、被一再回访。两套系统让它保持一致：绝不触发重新查询的 <span class="stat-hi">联动筛选</span>，以及一份清楚谁能编辑什么的 <span class="stat-hi">具所有权意识</span> 的 data apps 清单。',
        's05.filter.label': '筛选会串联，查询不重跑',
        's05.filter.body': '筛选是对话式的、而且彼此联动。"只看 New England"会更新每一张图，并把 VP 筛选器自动收窄到 New England 的 VP；Office 筛选器跟着动。"再筛到 Cathy Spinney"会把 By-VP 图收到她那条线、Office 筛选器收到她的 office。因为筛选是 <span class="stat-hi-blue">在既有结果集上的动态联动</span>，相关图表即时更新：不重新生成，也不为了每个小调整就重新查仓。',
        's05.own.label': '所有者 vs 被分享者',
        's05.own.body': '每一张在 Agent mode 里搭出来的画布，都会被自动加进它所在文件夹的 Data apps 清单。你能对一行做什么，取决于它是不是你搭的。所有者拿到完整菜单。对于只是被分享进你文件夹的 data app，<b>Edit 被刻意隐藏</b>：你打不开别人的来源对话，所以菜单提供 Start in new thread、Copy，以及一个只会从你自己文件夹移除它的 Delete。',
        's05.next.label': '接下来呢',
        's05.next.body': '有两项能力就在首发之外，已设计好、但定位为加分项而暂缓：<b>AI insight</b> 会用白话摘要为一张图加注，并为正在变动的数据标出"Where to focus"；以及 <b>排程式 Insight Reports</b>，按设定的频率把仪表板快照寄到 email 或推送，让这张活仪表板，也能触及那些从不打开画布的人。',
        's05.reflect': '回头看，Data Apps 其实不是在 mockup 里设计出来的。它是靠动手做被发掘出来、拿去和真实用户对撞测试，最后在几个小小的赌注上做出决定：对话该住在哪里、一个产出的单位该有多大。真正有意思的工作从来不是画图表，而是一次又一次地，选出那个能让使用它的人，清楚知道下一步该往哪走的版本。',
      },
      ja: {
        'nav.intro': '.イントロ', 'nav.s00': '01.発端', 'nav.s01': '02.探索', 'nav.s02': '03.対話', 'nav.s03': '04.Artifact', 'nav.s04': '05.ドリル', 'nav.s05': '06.ライフサイクル',
        'page.title': 'Data Apps',
        'page.subtitle': '対話で組み立て、直接操作で仕上げる、生きた BI キャンバス。',
        'intro.label.product': 'プロダクト概要｜対話型スマートダッシュボード',
        'intro.product.body': 'Data Apps は、AI を活用した「生きたダッシュボード」です。SQL を書いたりコンポーネントを手作業でドラッグしたりする必要はなく、分析したい内容を自然な言葉で伝えるだけです（例：「VP 別の目標達成率、地域で絞り込み可能」）。すると AI が、チャート・KPI・フィルター・ドリルダウン経路を備えた連動ダッシュボードを自動で組み立てます。一問一答だった従来の単発のデータ照会を、対話を続けながら動的に探索できる新しい BI 画面へと進化させました。',
        'intro.label.role': '私の役割｜エンドツーエンド (End-to-End) 体験デザイナー',
        'intro.role.body': 'Data Apps のキャンバス体験をゼロから 1 まで主導して設計しました。主な貢献は次のとおりです。<br><b>カスタマージャーニー全体の設計：</b><span class="stat-hi">13 のインタラクション段階</span> にわたるカスタマージャーニーマップ（Journey Map）を整理・設計し、対話による AI の起動、キャンバス生成、チャートのドリルダウンから、完成物の保存・共有・管理までをカバーしました。<br><b>デュアル操作モデルの設計：</b>「AI への対話指示」と「直接クリック操作」をシームレスに結びつけた二重の操作面を構築し、同じキャンバス上で最も直感的に編集とデータ探索を続けられるようにしました。',
        'intro.label.time': '期間：',
        'intro.time.body': '2026.4–2026.6',
        's00.title': 'すべての始まり',
        's00.lede': 'Data Apps は機能のアイデアから始まったのではなく、顧客のフィードバックから生まれました。定性インタビューでは、同じ光景が何度も浮かび上がりました。どのチームも、データアナリストが手作業で組み上げた数枚のダッシュボードに頼っていて、そのうち 1 枚を変える必要が出た瞬間、組織全体が <span class="stat-hi-blue">たった 1 人</span> の手待ちになってしまうのです。',
        's00.cap': '顧客自身のレポートの一例：データアナリストが Power BI で手作業で組み上げた GPS 完了率のダッシュボード。',
        's00.f1.label': '保守が難しい',
        's00.f1.body': '指標の微調整も、毎月の新しいデータも、壊れた join の修正も、すべてそのファイルを作ったアナリストに戻ってきます。ほかの誰も安全には触れません。',
        's00.f2.label': '構築コストが高い',
        's00.f2.body': 'ダッシュボード 1 枚にアナリストの数日がかかります：要件を集め、データをモデリングし、スライサーやドリル経路を 1 つずつ手作業でつないでいく。',
        's00.f3.label': '公開した瞬間に固まる',
        's00.f3.body': '公開後、レポートは事実上ロックされます。次元を 1 つ足す、切り口を変えるだけでも構築全体をやり直すことになり、ほとんどの変更要望は静かに消えていきました。',
        's00.close': 'そして別のチームが自分たちのビューを必要としても、自分では作れません。依頼を出し、アナリストの順番待ちに並び、たいていは諦めてしまう。Data Apps の最初の問いはそこから生まれました：レポートを必要とする本人が、ただ言葉で説明するだけで、本物の、生き続けるダッシュボードを受け取れたらどうだろう？',
        's01.title': 'Vibe Coding で探索し、ユーザーと共創する',
        's01.lede': 'Data Apps を静的なモックアップに描いて「これで合っているはず」と祈るのではなく、私は作って確かめる道を選びました。vibe coding を使えば、どのアイデアも数日でクリック可能なプロトタイプになります。それを実際の運用ユーザーの前に置き、その反応にフローを描き直してもらう。最終的にリリースしたのは、最初に描いた版ではなく、このループを生き延びた版です。',
        's01.body': 'このループは意図的に速く、雑であることを恐れませんでした。まず一つの版を vibe code で作り、ユーザーの隣に座って自分のデータで試す様子を眺め、どこでためらい、何に手を伸ばし、何を無視するかを観察します。ここでの共創はワークショップではありません。粗い版をまず出し、現実とぶつけて壊し、翌朝また作り直す。そうしてできた原型のうち二つは、並べて見る価値があります。その二つの隔たりこそが、すべての核心だからです。',
        's01.prior.label': '以前のやり方：一度に 1 枚ずつ',
        's01.prior.body': '実は手作業でも、ある程度までは到達できました。まず「各州の顧客による支払総額は？」のように質問し、テーブルが返ってきたら「グラフを 1 枚作って」と続けて棒グラフに変え、最後に <b>Pin to dashboard</b> を押して新しい「Payment Analysis Dashboard」を作成します。グラフはダッシュボードにピン留めされ、そのまま描画されます。',
        's01.prior.cost': 'けれどそれは 1 枚のグラフにすぎません。以前 BI ツールで組み上げたダッシュボードを再現するには、タイルごとにこのループをまるごと繰り返すことになり、しかも完成形のダッシュボードがどうあるべきかを最初から正確に把握し、各グラフをどんな質問で引き出すかを分かっている場合にだけ成り立ちます。以前のフローは答えてはくれても、計画そのものを代わりに背負ってはくれません。Data Apps はその差を埋めます：ダッシュボードを一度説明するだけで、キャンバスが連動した全体を組み上げます。',
        's01.now.label': '新しいやり方：コマンド 1 つでレポート全体',
        's01.now.body': 'いまは、手順ではなく目標を agent に渡します。<code>/generate-report</code> というコマンドを 1 つ実行し、ほしい成果を一行で伝えるだけです。たとえば「VP ごとの GPS 完成率を、オフィスと地域で分解」のように。あとは agent が自分で計画します。リクエストを複数の集計に分け、クエリを並列で実行し、切り口ごとに適したチャートを選び、1 つの完成レポートにまとめます。先ほどの一行だけで、かつて顧客が Power BI で手作業で組んでいた GPS 完成率レポートが出来上がりました：各 VP の目標に対する完成率の推移に、オフィスと地域の内訳を添えたもので、チャートを 1 つずつ指定することも SQL を書くこともありません。以前のフローが私に押し付けていた計画は、いまや agent の中にあります。',
        's01.flows.label': '同じダッシュボードへ向かう 2 つのバージョン',
        's01.flows.body': 'やるべきことは変わりません：チームには、使い続けられるダッシュボードが必要です。変わったのは、依頼する人がどれだけの作業を背負うかです。2 つのバージョンを通じて、計画の重みは依頼者からシステムへと移っていきました。',
        's01.f1.tag': 'Data Apps 以前',
        's01.f1.h': '依頼を出し、順番を待つ',
        's01.f1.s1': 'データアナリストに要望を伝える',
        's01.f1.s2': 'アナリストの待ち行列に並ぶ',
        's01.f1.s3': '結局あきらめることも多い',
        's01.f1.b': 'そのビューを必要とする本人には、作れませんでした。どのチームも手作業で組んだ数枚のダッシュボードに頼り、組織全体が 1 人のアナリストに詰まっていました。',
        's01.f2.tag': 'Ver. 1',
        's01.f2.h': 'Ask → Chart → Pin、一度に 1 枚ずつ',
        's01.f2.s1': '質問を 1 つして、テーブルを得る',
        's01.f2.s2': '「グラフを 1 枚作って」と頼んで描く',
        's01.f2.s3': 'Pin to dashboard を押し、また繰り返す',
        's01.f2.b': 'ようやく自分で扱えるようになりましたが、一度に 1 枚のグラフだけ。ダッシュボード全体を作り直すには、タイルごとにループをまるごと繰り返すことになり、しかも各質問を最初から分かっている場合にだけ成り立ちます。',
        's01.f3.tag': 'Ver. 2',
        's01.f3.h': 'コマンド 1 つ：/generate-report',
        's01.f3.s1': 'ほしい成果を一行で伝える',
        's01.f3.s2': 'agent が計画し、並列で実行',
        's01.f3.s3': '完成したレポートが届く',
        's01.f3.b': '渡すのは手順ではなく目標です。agent はリクエストを複数の集計に分け、並列で実行し、切り口ごとにチャートを選び、1 つの完成レポートを返します。',
        's01.flows.cap': 'たった 1 行の /generate-report が、この完全な GPS 完成率レポートを返しました：各 VP の目標に対する完成率の推移に、オフィスと地域のスライサーを添えています。',
        's01.old.h': '以前 · Ask Data',
        's01.old.lead': '1 つの質問 → 1 つの答え',
        's01.old.i1': '毎回ゼロから始まり、共有された状態がない',
        's01.old.i2': '答えは一度読まれたら、スクロールで流れ去る',
        's01.old.i3': 'チャート間で共有されるフィルターがない',
        's01.old.i4': '次元を変えるには、質問全体を問い直す必要がある',
        's01.new.h': '以後 · Data Apps Canvas',
        's01.new.lead': '1 つのプロンプト → 1 つの生きたダッシュボード',
        's01.new.i1': 'キャンバスはスレッド全体を通じて存在し続ける',
        's01.new.i2': 'チャート・KPI・フィルター・ドリル経路が連動し続ける',
        's01.new.i3': 'フィルターが一度にすべてのチャートへ連鎖する',
        's01.new.i4': 'すでにある対象に話しかけるだけで次元を変えられる',
        's02.title': '設計判断 1：対話インターフェースをどこに置くか',
        's02.lede': '私の最初の設計は、チャットパネルをダッシュボードの右側にドッキングするものでした。アシスタントを後付けした BI ツールならどれもそうしている、いかにも当然のレイアウトです。けれどそれは間違いでした。サイドパネルはキャンバスと幅を奪い合い、対話とそこから生まれた artifact を断ち切ってしまう。そこで私は対話を、その履歴をもともと保持している thread の中へ移し、その内側で操作を二つに分けました。なぜなら <span class="stat-hi">対話は意図を伝えるのは得意でも、精密な操作は苦手だ</span> からです。',
        's02.c.label': '意図は対話で',
        's02.c.body': 'チャット入力欄がキャンバス全体を動かします。ダッシュボードを言葉で表せば生成され、「7 月から 12 月だけ」と言えば全チャートが再同期し、「Cathy Spinney を展開」と言えばビューがドリルインします。メニューを探すより口で言うほうが速いものは、すべてここに属します。',
        's02.d.label': '精度は直接操作で',
        's02.d.body': 'けれどピクセル単位やチャートごとの作業は、文ではなく手の仕事です。<code>pick mode</code> のカーソルで任意のカード・KPI・フィルターバーをクリックすると、次のプロンプトの範囲をそのブロック 1 つに絞れます。鉛筆を押すと <span class="stat-hi-blue">そのチャートタイプ固有のコントロールだけを備えたインラインのスタイルパネル</span> が開きます：棒なら角丸、折れ線なら曲線タイプ、円ならドーナツの穴。使えないコントロールは決して表示されません。カードはドラッグで並べ替えでき、5px のしきい値を設けてあるので、ボタンのクリックが誤ってドラッグになることはありません。',
        's02.cap': 'Pick mode（↖）はプロンプトを 1 ブロックに絞り込む · 鉛筆はチャートタイプ固有のコントロールを開く',
        's03.title': '設計判断 2：「一つのダッシュボード」を「複数の artifact」に分ける',
        's03.lede': '最初の要件は「dashboard」、単数で書かれていました。あなたが生成し、所有する一枚の大きなボードです。けれどユーザーを見ていると、その概念は重すぎると感じました。彼らがほしいのは一枚岩ではなく、持ち運べて、再利用でき、共有できる断片でした。ここに一枚のチャート、あそこに一つの KPI、ある会議のための一枚のレポート。そこで私は成果物を捉え直しました。一つの Data App は一枚のダッシュボードではなく、<span class="stat-hi">それぞれ独立した複数の artifact</span> が、たまたま一つのキャンバスを共有しているものなのだ、と。',
        's03.body': 'それぞれの artifact を一級のオブジェクトとして扱うことは、システムが追跡すべきものを変えました。チャートはもう、それを生んだボードの中に閉じ込められていません。自分の識別子を持ち、自分の所有者を持ち、フォルダの中に自分の居場所を持ちます。だからこそ「Start in new thread」や「Copy to another folder」が意味を持ち、だからこそ共有はより鋭い問いに答えなければなりませんでした。「誰がこのボードを見られるか？」ではなく、「自分が作っていない artifact で、あなたは何ができるか？」という問いに。',
        's03.gen.label': '入り方は 3 通り、たどり着く先は 1 つ',
        's03.gen.body': 'そこから、3 種類の入力の質はすべて 1 つの完成したダッシュボードへ収束します。ユーザーが精密でも、曖昧でも、その中間でも、行き着く状態は同じです。',
        's03.precise.tag': '精密',
        's03.precise.h': '1 行で完全な仕様',
        's03.precise.b': '「VP 別・Office 別の GPS 完了率トレンド、region と VP で絞り込み可能」と書けば、ダッシュボード全体が一度に生成されます：2 つの折れ線チャート、月ナビゲーションバー、連動した Region → VP → Office のスライサー、障害トグル、そして一括クリア。',
        's03.vague.tag': '曖昧',
        's03.vague.h': 'ひと言足りない',
        's03.vague.b': '「GPS 完了率のダッシュボード」は確認の質問を 1 つだけ呼び起こします：「どの次元を分析したいですか？」VP、Office、Region、またはすべて、をワンタップのチップで選べます。',
        's03.clar.tag': '確認のあと',
        's03.clar.h': '行き先は同じ',
        's03.clar.b': '「すべて」をタップすると、精密なプロンプトが生んだのとまったく同じダッシュボードにたどり着きます。曖昧な経路はワンタップ余計にかかるだけで、やり直しは一度も要りません。',
        's03.roll.label': '止めずに転がる確認',
        's03.roll.body': '生成は、最初に許可を求めて立ち止まることがありません。チャートが描かれた瞬間、システムは次元の階層をスキャンし、流れを止めない 2 つの推奨ストリームを差し出します：<b>ドリルダウンの推奨</b>（「線をクリックしたあと何を表示すべき？」）と <b>チャートの推奨</b>（「region 別完了率の棒グラフも追加できます」）。1 つ受け入れれば追加され、残りはそのまま、スキップすれば畳まれます。ダッシュボードはどの段階でも使えます。これは Wren AI の Agent mode を支えるのと同じ <span class="stat-hi-blue">ローリング確認</span> パターンです。',
        's04.title': 'ドリルダウンという難題',
        's04.lede': 'ドリルダウンは、正しく仕上げるのが最も難しい単一のインタラクションでした。チャートはドリルできても、システムは <span class="stat-hi">クリックの次にどこへ行くべきか</span> をめったに知りません。かといって、すべての階層を前もって定義させると「説明するだけ」という魔法が台無しになります。答えは、階層を 3 つの入り口を持つ <span class="stat-hi-blue">ジャストインタイムの決定</span> にすることでした。',
        's04.e1.t': 'システムの推奨',
        's04.e1.b': 'チャートが描かれると同時に、システムはドリル可能な次元を検出し、次のレベルをその場で提案します。「Transaction detail」を受け入れれば、ユーザーが頼む前にドリル経路が設定されます。',
        's04.e2.t': 'プロンプトで宣言',
        's04.e2.b': '「地域別の売上、クリックしたら office にドリルダウン」と言えば、チャートを組む時点で階層が記録されます。ドリルのアイコンはすぐに現れます。追加の設定ステップは不要です。',
        's04.e3.t': '初回トリガー',
        's04.e3.b': 'ユーザーが一度も設定していないチャートをドリルします（「Bayville を展開」）。システムはそれを受け止めます：「このチャートにはドリルダウンが未設定です。展開したあと、何を見たいですか？」答えると、階層を記録し、同じ動作のままドリルインします。',
        's04.chain.label': '経路が連鎖するとき',
        's04.chain.body': '多階層の経路では、<code>Drill down:</code> と入力すると連鎖式のレベルピッカーが開きます。「By Region」を選ぶと入力が <code>Drill down: By Region → /</code> になり再び開きます。次に「By Office」を選びます。選択済みのレベルは重複防止のため非表示になり、パンくずヘッダーがここまでの経路を示し、Enter で連鎖全体が一度に適用されます。',
        's04.undef.label': '次元に次のレベルがないとき',
        's04.undef.body': '軸の中には明確な子を持たないものもあります。「Month」軸をドリルすると、システムは正直に認めます：「Month には事前定義された次のレベルがありません。展開時にどのフィールドを表示しますか？」Week、Day、またはフィールド一覧から選択。正直な行き止まりが、沈黙の失敗ではなく、ワンタップの決定になります。',
        's04.hier.label': '土台にある階層',
        's04.hier.body': 'これらすべては、明示的な親子モデルの上に成り立っています：データレベルで集計と展開を定義する <code>Hierarchy Instruction</code> レイヤーがあるため、クリックは常に正しく集約されたビューに着地します。ローンチ用データセットの重要なドリル経路は 5 階層の深さに及びます：',
        's04.cap': 'クリックごとに 1 階層ずつ集約され、パンくずとロジックトラッカーが現在の経路を常に明示します。',
        's05.title': '生き続けるダッシュボード',
        's05.lede': 'ダッシュボードはいったん残ると、生命を持ちます：フィルターされ、共有され、分岐され、何度も見直されます。2 つの仕組みがそれを整合させます：再クエリを一切起こさない <span class="stat-hi">連鎖フィルター</span> と、誰が何を編集できるかを把握する <span class="stat-hi">オーナーシップを意識した</span> data apps の一覧です。',
        's05.filter.label': 'フィルターは連鎖し、クエリは繰り返さない',
        's05.filter.body': 'フィルターは対話的で、互いに連動します。「New England だけ表示」と言えば全チャートが更新され、VP スライサーは New England の VP へ自動的に絞り込まれ、Office スライサーもそれに続きます。「さらに Cathy Spinney で絞り込み」と言えば、By-VP チャートは彼女の線に、Office スライサーは彼女の office に絞られます。フィルターは <span class="stat-hi-blue">既存の結果セット上の動的な連動</span> なので、関連チャートは即座に更新されます。全体の再生成もなく、調整のたびに warehouse へ問い合わせ直すこともありません。',
        's05.own.label': 'オーナーと共有された側',
        's05.own.body': 'Agent mode で作られたキャンバスは、すべてそのフォルダの Data apps 一覧へ自動的に追加されます。ある行に何ができるかは、それを自分が作ったかどうかで決まります。オーナーはフルメニューを得ます。あなたのフォルダへ共有されただけの data app では、<b>Edit は意図的に隠されます</b>。他人のソーススレッドは開けないからです。そのためメニューには Start in new thread、Copy、そして自分のフォルダからのみ削除する Delete が並びます。',
        's05.next.label': '次に来るもの',
        's05.next.body': 'ローンチのすぐ先に、設計は済んでいるものの nice-to-have として段階を待つ機能が 2 つあります：チャートに平易な要約と、動いているデータへの「Where to focus」マーカーを添える <b>AI insight</b>、そして設定した頻度でダッシュボードのスナップショットを email やプッシュで届ける <b>スケジュール型 Insight Reports</b>。キャンバスを一度も開かない人にも、この生きたダッシュボードが届くように。',
        's05.reflect': '振り返ると、Data Apps はモックアップの中で設計されたわけではありませんでした。作ることで見つかり、実際のユーザーにぶつけて試され、そしていくつかの小さな賭けの中で決まっていきました。対話はどこに住むべきか、成果物の一単位はどれくらいの大きさであるべきか。面白い仕事は、チャートを描くことでは決してありませんでした。それは、使う人に次の一手をはっきり残してくれる版を、何度も何度も選び続けることでした。',
      },
      'en': {
        'nav.intro': '.Intro', 'nav.s00': '01.Origin', 'nav.s01': '02.Explore', 'nav.s02': '03.Thread', 'nav.s03': '04.Artifacts', 'nav.s04': '05.Drill', 'nav.s05': '06.Lifecycle',
        'page.title': 'Data Apps',
        'page.subtitle': 'A living BI canvas you build by conversation, and refine by direct manipulation.',
        'intro.label.product': 'Product | Conversational BI Dashboard',
        'intro.product.body': 'Data Apps is an AI-powered “living dashboard.” Instead of writing SQL or dragging widgets by hand, you describe what you need in plain language (for example, “target attainment by VP, filterable by region”), and the AI assembles a connected dashboard of charts, KPIs, filters, and drill-down paths. It turns the old one-question-at-a-time data lookup into a new kind of BI surface you can keep talking to and explore on the fly.',
        'intro.label.role': 'My Role | End-to-End Experience Designer',
        'intro.role.body': 'I led the Canvas experience design for Data Apps from 0 to 1. My main contributions:<br><b>Mapping the full user journey:</b> I structured and designed a customer journey map spanning <span class="stat-hi">13 interaction stages</span>, from waking the AI through conversation, generating the canvas, and drilling into charts, to saving, sharing, and managing the finished product.<br><b>Designing a dual-control interaction model:</b> I built a control surface that seamlessly combines “AI conversational commands” with “direct click manipulation,” letting users keep editing and exploring data on the same canvas in the most intuitive way.',
        'intro.label.time': 'TimeFrame:',
        'intro.time.body': 'Apr–Jun 2026',
        's00.title': 'Where It Started',
        's00.lede': 'Data Apps didn’t begin as a feature idea. It began in customer feedback. In qualitative interviews, the same picture kept surfacing: every team leaned on a handful of dashboards hand-built by a data analyst, and the moment one needed to change, the whole organization was stuck waiting on <span class="stat-hi-blue">one person</span>.',
        's00.cap': 'A representative example of one of the customer’s own reports: a GPS-completeness dashboard hand-built in Power BI by a data analyst.',
        's00.f1.label': 'Hard to maintain',
        's00.f1.body': 'Every metric tweak, every new month of data, every broken join went back to the analyst who built the file. No one else could safely touch it.',
        's00.f2.label': 'Expensive to build',
        's00.f2.body': 'A single dashboard took days of analyst time: gathering requirements, modeling the data, and wiring up slicers and drill paths by hand.',
        's00.f3.label': 'Frozen once shipped',
        's00.f3.body': 'After launch the report was effectively locked. A new dimension or a different cut meant re-opening the whole build, so most change requests quietly died.',
        's00.close': 'And when another team needed its own view, they couldn’t make it themselves. They filed a request, waited in the analyst’s queue, and often gave up. That was the opening question behind Data Apps: what if the person who needs the report could simply describe it, and get a real, living dashboard back?',
        's01.title': 'Vibe Coding the Exploration',
        's01.lede': 'Instead of speccing Data Apps in static mockups and hoping it felt right, I built it to find out. With vibe coding, I turned each idea into a clickable prototype within days, put it in front of real operations users, and let their reactions redraw the flow. What shipped is the version that survived that loop, not the one I sketched first.',
        's01.body': 'The loop was deliberately fast and unprecious. I would vibe-code a version, sit with users while they tried it on their own data, and watch where they hesitated, what they reached for, and what they ignored. Co-creation here was not a workshop, it was shipping a rough build, breaking it on contact with reality, and rebuilding the next morning. Two of those prototyped versions are worth putting side by side, because the distance between them is the whole point.',
        's01.prior.label': 'The old way: one chart at a time',
        's01.prior.body': 'You could already get part of the way there by hand. Ask a question like “What’s the total value of payments by customers in each state?”, wait for the table to come back, follow up with “Generate a chart for me” to turn it into a bar chart, then hit <b>Pin to dashboard</b> and spin up a new “Payment Analysis Dashboard.” The chart lands on the dashboard, pinned and fully rendered.',
        's01.prior.cost': 'But that was one chart. To rebuild a dashboard you had already assembled in a BI tool, you ran the whole loop again for every tile, and it only worked if you knew up front exactly what the finished dashboard should contain and how to phrase each question to pull each chart out. The old flow could answer; it could not plan for you. Data Apps closes that gap: you describe the dashboard once and the canvas assembles the connected whole.',
        's01.now.label': 'The new way: one command, the whole report',
        's01.now.body': 'Now you hand the agent the goal instead of the steps. You run one command, <code>/generate-report</code>, and describe the outcome in a line, like “GPS completion rate by VP, broken down by office and region.” The agent plans the rest itself: it splits the request into separate aggregations, runs the queries in parallel, picks a fitting chart for each cut, and assembles them into one finished report. That single line produced the kind of GPS-completeness report customers used to hand-build in Power BI: each VP’s completion trend against target, with office and region breakdowns, without my naming each chart or writing any SQL. The planning the old flow pushed onto me now lives inside the agent.',
        's01.flows.label': 'Two versions, the same dashboard',
        's01.flows.body': 'The job never changed: a team needs a dashboard it can keep using. What changed is how much of the work the person asking has to carry. Across the two versions, the planning moved off the requester and into the system.',
        's01.f1.tag': 'Before Data Apps',
        's01.f1.h': 'File a request, wait in the queue',
        's01.f1.s1': 'Describe the need to a data analyst',
        's01.f1.s2': 'Wait in the analyst’s backlog',
        's01.f1.s3': 'Often give up',
        's01.f1.b': 'The person who needed the view couldn’t build it. Every team leaned on a few hand-built dashboards, and the whole org was blocked on one analyst.',
        's01.f2.tag': 'Ver. 1',
        's01.f2.h': 'Ask → Chart → Pin, one tile at a time',
        's01.f2.s1': 'Ask one question, get a table',
        's01.f2.s2': '“Generate a chart” to plot it',
        's01.f2.s3': 'Pin to dashboard, then repeat',
        's01.f2.b': 'Finally self-serve, but it answered one chart at a time. Rebuilding a full dashboard meant running the whole loop for every tile, and only if you knew each question up front.',
        's01.f3.tag': 'Ver. 2',
        's01.f3.h': 'One command: /generate-report',
        's01.f3.s1': 'Describe the outcome in a line',
        's01.f3.s2': 'Agent plans and runs in parallel',
        's01.f3.s3': 'A finished report lands',
        's01.f3.b': 'You hand over the goal, not the steps. The agent splits the request into separate aggregations, runs them in parallel, picks a chart per cut, and returns one finished report.',
        's01.flows.cap': 'One /generate-report line returned this full GPS-completeness report: each VP’s completion trend against target, with office and region slicers.',
        's01.old.h': 'Before · Ask Data',
        's01.old.lead': 'One question → one answer',
        's01.old.i1': 'Each turn starts cold, with no shared state',
        's01.old.i2': 'The answer is read once, then scrolls away',
        's01.old.i3': 'No filters shared between charts',
        's01.old.i4': 'Re-ask the whole question to change a dimension',
        's01.new.h': 'After · Data Apps Canvas',
        's01.new.lead': 'One prompt → one living dashboard',
        's01.new.i1': 'The canvas persists across the whole thread',
        's01.new.i2': 'Charts, KPIs, filters and drill paths stay connected',
        's01.new.i3': 'Filters cascade across every chart at once',
        's01.new.i4': 'Change a dimension by talking to what’s already there',
        's02.title': 'Decision 1: Conversation in the Thread',
        's02.lede': 'My first design docked a chat panel to the right of the dashboard, the obvious layout, borrowed from every BI tool with an assistant bolted on. It was wrong: a side panel fights the canvas for width, and it severs the conversation from the artifact it produced. So I moved the conversation into the thread that already holds its history, and let control split two ways inside it, because <span class="stat-hi">conversation is great for intent, and terrible for precision.</span>',
        's02.c.label': 'Conversation for intent',
        's02.c.body': 'The chat input drives the entire canvas. Describe a dashboard and it’s generated; say “show only July through December” and every chart re-syncs; say “expand Cathy Spinney” and the view drills in. Anything faster to say than to find in a menu lives here.',
        's02.d.label': 'Direct manipulation for precision',
        's02.d.body': 'But pixel-level and per-chart work belongs to the hands, not the sentence. A <code>pick mode</code> cursor lets you click any card, KPI, or the filter bar to scope the next prompt to that one block. A pencil opens an <span class="stat-hi-blue">inline style panel whose controls are specific to that chart type</span>: corner radius for bars, curve type for lines, donut hole for pies, so a control you can’t use is never shown. Cards drag to reorder, with a 5px threshold so a button click never starts a drag by accident.',
        's02.cap': 'Pick mode (↖) scopes a prompt to one block · the pencil opens chart-type-specific controls',
        's03.title': 'Decision 2: One Dashboard, Many Artifacts',
        's03.lede': 'The brief said “dashboard,” singular: one big board you generate and own. Watching users, the concept felt too heavy. They didn’t want a monolith; they wanted pieces they could lift, reuse, and share, a chart here, a KPI there, a report for one meeting. So I reframed the output: a Data App isn’t one dashboard but <span class="stat-hi">many independent artifacts</span> that happen to share a canvas.',
        's03.body': 'Treating each artifact as a first-class object changed what the system had to track. A chart is no longer trapped in the board that produced it: it has its own identity, its own owner, and its own place in a folder. That is what makes “Start in new thread” or “Copy to another folder” mean something, and it is why sharing had to answer a sharper question. Not “who can see this board?” but “what can you do with an artifact you didn’t build?”',
        's03.gen.label': 'Three ways in, one good outcome',
        's03.gen.body': 'From there, three input qualities all converge on a complete dashboard: the same end state whether the user is precise, vague, or somewhere in between.',
        's03.precise.tag': 'Precise',
        's03.precise.h': 'Full spec in one line',
        's03.precise.b': '“GPS Completeness trend by VP and by Office, filterable by region and VP” generates the whole dashboard in one step: both line charts, a month-navigation bar, linked Region → VP → Office slicers, an outage toggle, and a clear-all.',
        's03.vague.tag': 'Vague',
        's03.vague.h': 'One word short',
        's03.vague.b': '“GPS completion rate dashboard” triggers a single clarifying question, “Which dimensions do you want to analyze?”, with VP, Office, Region, or All of the above as one-tap chips.',
        's03.clar.tag': 'After clarifying',
        's03.clar.h': 'Same destination',
        's03.clar.b': 'Tapping “All of the above” lands on exactly the dashboard the precise prompt produced. The vague path costs one extra tap, never a restart.',
        's03.roll.label': 'Confirmation that rolls, not blocks',
        's03.roll.body': 'Generation never stops to ask permission up front. The moment charts render, the system scans the dimension hierarchy and surfaces two non-blocking recommendation streams: a <b>drill-down recommendation</b> (“what should appear after clicking a line?”) and <b>chart recommendations</b> (“you could also add a completion-by-region bar”). Accept one and it’s added; the rest stay; skip and they collapse. The dashboard is usable at every step. It’s the same <span class="stat-hi-blue">rolling-confirmation</span> pattern that anchors Wren AI’s Agent mode.',
        's04.title': 'The Drill-Down Problem',
        's04.lede': 'Drill-down was the single hardest interaction to get right. A chart can be drilled, but the system rarely knows <span class="stat-hi">where a click should go next</span>, and forcing users to define every hierarchy up front kills the magic of “just describe it.” The answer was to make hierarchy a <span class="stat-hi-blue">just-in-time decision</span> with three entry points.',
        's04.e1.t': 'System recommendation',
        's04.e1.b': 'As charts render, the system detects drillable dimensions and proposes the next level inline. Accept “Transaction detail” and the drill path is configured before the user even asks.',
        's04.e2.t': 'Declared in the prompt',
        's04.e2.b': '“Regional sales, clicking should drill to offices” records the hierarchy as the chart is built. The drill icon appears immediately. No extra setup step.',
        's04.e3.t': 'First-time trigger',
        's04.e3.b': 'The user drills a chart that was never configured (“Expand Bayville”). The system catches it: “this chart has no drill-down set: after expanding, what do you want to see?” On answer, it records the hierarchy and drills in the same motion.',
        's04.chain.label': 'When the path is chained',
        's04.chain.body': 'For multi-level paths, typing <code>Drill down:</code> opens a chained level picker. Pick “By Region” and the input becomes <code>Drill down: By Region → /</code> and reopens; pick “By Office” next. Already-chosen levels are hidden to prevent duplicates, a breadcrumb header shows the path so far, and Enter applies the whole chain at once.',
        's04.undef.label': 'When the dimension has no next level',
        's04.undef.body': 'Some axes have no obvious child. Drill a “Month” axis and the system admits it: “Month has no predefined next level: what field should expanding show?” with Week, Day, or Choose from field list. An honest dead-end becomes a one-tap decision instead of a silent failure.',
        's04.hier.label': 'The hierarchy underneath',
        's04.hier.body': 'All of this rests on an explicit parent–child model: a <code>Hierarchy Instruction</code> layer that defines aggregation and expansion at the data level, so a click always lands on a correctly rolled-up view. The critical drill path for the launch dataset runs five levels deep:',
        's04.cap': 'Each click aggregates one level down; the breadcrumb and a logic tracker keep the current path explicit.',
        's05.title': 'Dashboards That Stay Alive',
        's05.lede': 'Once a dashboard persists, it has a life: it gets filtered, shared, branched, and revisited. Two systems keep it coherent: <span class="stat-hi">cascading filters</span> that never trigger a re-query, and an <span class="stat-hi">ownership-aware</span> data-apps list that knows who can edit what.',
        's05.filter.label': 'Filters cascade, queries don’t repeat',
        's05.filter.body': 'Filtering is conversational and connected. “Show only New England” updates every chart and auto-narrows the VP slicer to New England VPs; the Office slicer follows. “Also filter to Cathy Spinney” narrows the By-VP chart to her line and the Office slicer to her offices. Because filters are <span class="stat-hi-blue">dynamic linkage over the existing result set</span>, related charts update instantly: no full regeneration, no re-querying the warehouse for every tweak.',
        's05.own.label': 'Owner versus shared',
        's05.own.body': 'Every canvas built in Agent mode is auto-added to its folder’s Data apps list. What you can do to a row depends on whether you built it. Owners get the full menu. For a data app merely shared into your folder, <b>Edit is intentionally hidden</b>: you can’t open someone else’s source thread, so the menu offers Start in new thread, Copy, and a Delete that only removes it from your own folder.',
        's05.next.label': 'What comes next',
        's05.next.body': 'Two capabilities sit just beyond launch, designed but staged as nice-to-haves: <b>AI insight</b> that annotates a chart with a plain-language summary and a “Where to focus” marker for the data that’s moving, and <b>scheduled Insight Reports</b> that deliver a dashboard snapshot to email or push on a set cadence, so the living dashboard can reach people who never open the canvas.',
        's05.reflect': 'Looking back, Data Apps wasn’t really designed in mockups. It was discovered by building, tested against real users, and decided in a handful of small bets: where the conversation should live, and how big a single unit of output should be. The interesting work was never drawing charts; it was choosing, over and over, the version that left the person using it with an obvious next move.',
      },
    };

    const dataAppsRichKeys = [
      'intro.role.body',
      's00.lede',
      's01.lede','s01.prior.body','s01.now.body',
      's02.lede','s02.d.body',
      's03.lede','s03.body','s03.roll.body',
      's04.lede','s04.chain.body','s04.hier.body',
      's05.lede','s05.filter.body','s05.own.body','s05.next.body',
    ];

    const dataAppsOriginals = {};
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      dataAppsOriginals[key] = dataAppsRichKeys.includes(key) ? el.innerHTML : el.textContent;
    });

    function applyDataAppsLang(lang) {
      const t = dataAppsI18n[lang];
      if (!t || lang === 'en') {
        document.querySelectorAll('[data-i18n]').forEach(el => {
          const key = el.getAttribute('data-i18n');
          if (dataAppsOriginals[key] !== undefined) {
            if (dataAppsRichKeys.includes(key)) el.innerHTML = dataAppsOriginals[key];
            else el.textContent = dataAppsOriginals[key];
          }
        });
        document.documentElement.lang = 'en';
        return;
      }
      document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key] !== undefined) {
          if (dataAppsRichKeys.includes(key)) el.innerHTML = t[key];
          else el.textContent = t[key];
        }
      });
      document.documentElement.lang = lang === 'zh-tw' ? 'zh-TW' : lang === 'zh-cn' ? 'zh-CN' : lang;
    }

    try {
      const saved = localStorage.getItem('portfolio-lang');
      if (saved && saved !== 'en') applyDataAppsLang(saved);
      const sel = document.getElementById('nav-lang-select');
      if (sel) sel.value = saved || 'en';
    } catch(e) {}

    const langSel = document.getElementById('nav-lang-select');
    if (langSel) {
      langSel.addEventListener('change', () => {
        const lang = langSel.value;
        applyDataAppsLang(lang);
        try { localStorage.setItem('portfolio-lang', lang); } catch(e) {}
      });
    }
  })();
